---
- name: Create applications SJC PME Lab F5 Networks
  hosts: all
  connection: local

  tasks:
    - name: site10waf.example.com
      bigiq_application_https_waf:
        provider:
          server: 10.192.75.180
          user: admin
          password: admin
          validate_certs: no
        name: "site10waf.example.com"
        wait: no
        description: Load balance WAF
        service_environment: "bigiptier1.lab.fp.f5net.com"
        domain_names: "site10.example.com"
        add_analytics: yes
        servers:
          - address: 10.1.20.201
            port: 80
          - address: 10.1.20.202
            port: 80
        inbound_virtual:
          address: 10.1.10.201
          netmask: 255.255.255.255
          port: 443
        redirect_virtual:
          address: 10.1.10.201
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site12http.example.com
      bigiq_application_http:
        provider:
          server: 10.192.75.180
          user: admin
          password: admin
          validate_certs: no
        name: "site12http.example.com"
        wait: no
        description: Load balance HTTP
        service_environment: "bigiptier1.lab.fp.f5net.com"
        add_analytics: yes
        servers:
          - address: 10.1.20.201
            port: 8081
        inbound_virtual:
          address: 10.1.10.202
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site14https.example.com
      bigiq_application_https_offload:
        provider:
          server: 10.192.75.180
          user: admin
          password: admin
          validate_certs: no
        name: "site14https.example.com"
        wait: no
        description: Load balance HTTPS Offload
        service_environment: "bigiptier1.lab.fp.f5net.com"
        add_analytics: yes
        servers:
          - address: 10.1.20.202
            port: 80
          - address: 10.1.20.203
            port: 80
        inbound_virtual:
          address: 10.1.10.203
          netmask: 255.255.255.255
          port: 443
        redirect_virtual:
          address: 10.1.10.203
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site15fasthttp.example.com
      bigiq_application_fasthttp:
        provider:
          server: 10.192.75.180
          user: admin
          password: admin
          validate_certs: no
        name: "site15fasthttp.example.com"
        wait: no
        description: Load balance Fast HTTP
        service_environment: "bigiptier1.lab.fp.f5net.com"
        add_analytics: yes
        servers:
          - address: 10.1.20.204
            port: 80
          - address: 10.1.20.205
            port: 80
        inbound_virtual:
          address: 10.1.10.204
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site16fastL4tcp.example.com
      bigiq_application_fastl4_tcp:
        provider:
          server: 10.192.75.180
          user: admin
          password: admin
          validate_certs: no
        name: "site16fasL4.example.com"
        wait: no
        description: Load balance Fast L4 TCP
        service_environment: "bigiptier1.lab.fp.f5net.com"
        servers:
          - address: 10.1.20.206
            port: 8081
          - address: 10.1.20.207
            port: 8081
        inbound_virtual:
          address: 10.1.10.205
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site18udp.example.com
      bigiq_application_fastl4_udp:
        provider:
          server: 10.192.75.180
          user: admin
          password: admin
          validate_certs: no
        name: "site18udp.example.com"
        wait: no
        description: Load balance Fast UDP
        service_environment: "bigiptier1.lab.fp.f5net.com"
        servers:
          - address: 10.1.20.206
            port: 8090
          - address: 10.1.20.207
            port: 8090
        inbound_virtual:
          address: 10.1.10.206
          netmask: 255.255.255.255
          port: 53
      delegate_to: localhost