---
- name: Create applications Seattle PME Lab F5 Networks
  hosts: all
  connection: local

  tasks:
    - name: site10waf.example.com
      bigiq_application_https_waf:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site10waf.example.com"
        wait: no
        description: Load balance WAF
        service_environment: "008-bigip-01.example.com"
        domain_names: "site10.example.com"
        add_analytics: yes
        servers:
          - address: 10.101.51.51
            port: 80
          - address: 10.101.51.52
            port: 80
        inbound_virtual:
          address: 10.101.50.214
          netmask: 255.255.255.255
          port: 443
        redirect_virtual:
          address: 10.101.50.214
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site12http.example.com
      bigiq_application_http:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site12http.example.com"
        wait: no
        description: Load balance HTTP
        service_environment: "008-bigip-01.example.com"
        add_analytics: yes
        servers:
          - address: 10.101.51.51
            port: 8081
        inbound_virtual:
          address: 10.101.50.215
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site14https.example.com
      bigiq_application_https_offload:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site14https.example.com"
        wait: no
        description: Load balance HTTPS Offload
        service_environment: "008-bigip-01.example.com"
        add_analytics: yes
        servers:
          - address: 10.101.51.52
            port: 80
          - address: 10.101.51.53
            port: 80
        inbound_virtual:
          address: 10.101.50.216
          netmask: 255.255.255.255
          port: 443
        redirect_virtual:
          address: 10.101.50.216
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site15fasthttp.example.com
      bigiq_application_fasthttp:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site15fasthttp.example.com"
        wait: no
        description: Load balance Fast HTTP
        service_environment: "008-bigip-01.example.com"
        add_analytics: yes
        servers:
          - address: 10.101.51.54
            port: 80
          - address: 10.101.51.55
            port: 80
        inbound_virtual:
          address: 10.101.50.217
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site16fastL4tcp.example.com
      bigiq_application_fastl4_tcp:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site16fasL4.example.com"
        wait: no
        description: Load balance Fast L4 TCP
        service_environment: "008-bigip-01.example.com"
        servers:
          - address: 10.101.51.56
            port: 8081
          - address: 10.101.51.57
            port: 8081
        inbound_virtual:
          address: 10.101.50.218
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site18udp.example.com
      bigiq_application_fastl4_udp:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site18udp.example.com"
        wait: no
        description: Load balance Fast UDP
        service_environment: "008-bigip-01.example.com"
        servers:
          - address: 10.101.51.56
            port: 8090
          - address: 10.101.51.57
            port: 8090
        inbound_virtual:
          address: 10.101.50.219
          netmask: 255.255.255.255
          port: 53
      delegate_to: localhost